### ISSUE TITLE
the addon doesn't work

### ISSUE THREAD

**Issue by ESM-96** [sleeyax/stremio-horriblesubs-addon#7]
hi, the addon doesn't work anymore in stremio.
ca you fix this please?

**Comment by sleeyax** [comment]
All of my addons went down since now.sh (hosting provider) banned me and a few other addon developers from the service. I'll close this issue when they are back online. Keep an eye on the [r/stremioaddons](https://www.reddit.com/r/StremioAddons/comments/fnnkkx/news_a_large_number_of_addons_are_currently/) subreddit for more news on the situation, thanks.

**Comment by sleeyax** [comment]
@ESM-96 The addon is back online at the following URL: https://more-milk.xyz/horriblesubs/manifest.json
Please keep an eye on the subreddit for the announcement & more info.

You can read more about what happened [here](https://more-milk.xyz).

**Comment by ESM-96** [comment]
hi, the addon doesn't work... 
i add the addon with this URL https://more-milk.xyz/horriblesubs/manifest.json like you said to do.
i can search the anime i want to see but doesn´t work.
